version: "3.1"
services:
  mongo:
    image: "mongo:4.4.3"
    restart: always
    ports:
    - "27017:27017"
  postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_DB: "graduation_work"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
  graduation_work:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    depends_on:
      - "postgres"
      - "minio"
      - "mongo"
    links:
      - "postgres"
      - "minio"
      - "mongo"
    ports:
      - "9099:8080"
  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
#    volumes:
#      - ./minio/data:/data
#      - ./minio/log:/var/log
    environment:
      MINIO_ACCESS_KEY: graduation_work_minio_access_key
      MINIO_SECRET_KEY: graduation_work_minio_super_duper_secret_key
      MINIO_HTTP_TRACE: /var/log/minio.log
    command: server /data